# Generated by Django 3.0.5 on 2020-04-19 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(help_text='Please enter a valid email address.', max_length=254, verbose_name='Contact Email')),
                ('contact_first_name', models.CharField(help_text='That being other than the others.', max_length=60, verbose_name='First Name')),
                ('contact_last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('topic', models.CharField(choices=[('a', 'Enquiries'), ('b', 'Comments'), ('c', 'Site Bugs')], default='a', max_length=12, verbose_name='Topic')),
                ('subject', models.CharField(max_length=60, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contact_message',
                'verbose_name_plural': 'contacts_messages',
                'ordering': ['message_date'],
            },
        ),
    ]
